export const GET_CART = 'GET_CART';
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const GET_PRODUCTS_CATEGORY = 'GET_PRODUCTS_CATEGORY';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const ADD_CATEGORY = 'GET_CATEGORY';
